import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {
	ClerkProvider,
	SignInButton,
	SignedIn,
	SignedOut,
	UserButton,
} from "@clerk/nextjs";
import "./globals.css";
import { QueryProvider } from "@/providers/query-provider";
import SheetProvider from "@/providers/sheet-provider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider>
			<html lang="en">
				<body className={inter.className}>
					{/*  passing the children inside the query provider which is a client component will make the children a client component, thi sis a feature inside next js that you can safely pass server children inside a client component and they will stay as server components */}
					<QueryProvider>
						<SheetProvider />
						{children}
					</QueryProvider>
				</body>
			</html>
		</ClerkProvider>
	);
}
